## AUTO-GENERATED by convert_script.py — 不要手改，重跑转换器会覆盖。
## 王霜立绘：素材在本目录下按 <姿势>(<表情>.png 命名，扫描自动注册。
## 摆位参数改 convert_script.py 里的 WS_* 常量。

image ws akimbo proud = "images/sprites/叉腰表情/叉腰（得意.png"
image ws akimbo blank = "images/sprites/叉腰表情/叉腰（面无表情.png"
image ws akimbo default = "images/sprites/叉腰表情/叉腰（默认.png"
image ws crossed smirk = "images/sprites/抱胸表情/抱胸(坏笑.png"
image ws crossed wry = "images/sprites/抱胸表情/抱胸(无奈.png"
image ws crossed blank = "images/sprites/抱胸表情/抱胸(面无表情.png"
image ws crossed default = "images/sprites/抱胸表情/抱胸(默认.png"
image ws backhand shocked = "images/sprites/背手表情/背手(吃惊.png"
image ws backhand smirk = "images/sprites/背手表情/背手(坏笑.png"
image ws backhand blank = "images/sprites/背手表情/背手(面无表情).png"
image ws backhand default = "images/sprites/背手表情/背手(默认.png"

image ws akimbo default_glitch:
    "images/sprites/glitch/叉腰（默认_glitch1.png"
    0.12
    "images/sprites/glitch/叉腰（默认_glitch2.png"
    0.12
    "images/sprites/glitch/叉腰（默认_glitch3.png"
    0.12
    repeat

image ws crossed smirk_glitch:
    "images/sprites/glitch/抱胸(坏笑_glitch1.png"
    0.12
    "images/sprites/glitch/抱胸(坏笑_glitch2.png"
    0.12
    "images/sprites/glitch/抱胸(坏笑_glitch3.png"
    0.12
    repeat

image ws crossed default_glitch:
    "images/sprites/glitch/抱胸(默认_glitch1.png"
    0.12
    "images/sprites/glitch/抱胸(默认_glitch2.png"
    0.12
    "images/sprites/glitch/抱胸(默认_glitch3.png"
    0.12
    repeat

image ws backhand default_glitch:
    "images/sprites/glitch/背手(默认_glitch1.png"
    0.12
    "images/sprites/glitch/背手(默认_glitch2.png"
    0.12
    "images/sprites/glitch/背手(默认_glitch3.png"
    0.12
    repeat

## 半身近景（第一人称对视感）：头到腰占满屏，底部裁掉，水平居中。
transform ws_close:
    xalign 0.5
    yanchor 0.0
    ypos -50
    zoom 0.52
