## AUTO-GENERATED by convert_script.py — 不要手改，重跑转换器会覆盖。
## 立绘素材按角色分文件夹：王霜/（按 <姿势>(<表情>.png 命名，递归扫描）、
## 尤里娅/（平铺，<角色名>(<表情>.png；尤利娅尸首.png = 尸首形态）。
## 摆位参数改 convert_script.py 里的 WS_* / YL_* 常量。

image ws akimbo proud = "images/sprites/王霜/叉腰表情/叉腰（得意.png"
image ws akimbo blank = "images/sprites/王霜/叉腰表情/叉腰（面无表情.png"
image ws akimbo default = "images/sprites/王霜/叉腰表情/叉腰（默认.png"
image ws crossed smirk = "images/sprites/王霜/抱胸表情/抱胸(坏笑.png"
image ws crossed wry = "images/sprites/王霜/抱胸表情/抱胸(无奈.png"
image ws crossed blank = "images/sprites/王霜/抱胸表情/抱胸(面无表情.png"
image ws crossed default = "images/sprites/王霜/抱胸表情/抱胸(默认.png"
image ws backhand shocked = "images/sprites/王霜/背手表情/背手(吃惊.png"
image ws backhand smirk = "images/sprites/王霜/背手表情/背手(坏笑.png"
image ws backhand blank = "images/sprites/王霜/背手表情/背手(面无表情).png"
image ws backhand default = "images/sprites/王霜/背手表情/背手(默认.png"

image ws akimbo blank_glitch:
    choice:
        "images/sprites/王霜/glitch/叉腰（面无表情_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/叉腰（面无表情_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/叉腰（面无表情_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws akimbo default_glitch:
    choice:
        "images/sprites/王霜/glitch/叉腰（默认_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/叉腰（默认_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/叉腰（默认_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed smirk_glitch:
    choice:
        "images/sprites/王霜/glitch/抱胸(坏笑_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(坏笑_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(坏笑_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed wry_glitch:
    choice:
        "images/sprites/王霜/glitch/抱胸(无奈_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(无奈_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(无奈_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed default_glitch:
    choice:
        "images/sprites/王霜/glitch/抱胸(默认_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(默认_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/抱胸(默认_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand smirk_glitch:
    choice:
        "images/sprites/王霜/glitch/背手(坏笑_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/背手(坏笑_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/背手(坏笑_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand default_glitch:
    choice:
        "images/sprites/王霜/glitch/背手(默认_glitch1.png"
    choice:
        "images/sprites/王霜/glitch/背手(默认_glitch2.png"
    choice:
        "images/sprites/王霜/glitch/背手(默认_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws akimbo proud_unglitch:
    "images/sprites/王霜/叉腰表情/叉腰（得意.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws akimbo blank_unglitch:
    "images/sprites/王霜/叉腰表情/叉腰（面无表情.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws akimbo default_unglitch:
    "images/sprites/王霜/叉腰表情/叉腰（默认.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed smirk_unglitch:
    "images/sprites/王霜/抱胸表情/抱胸(坏笑.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed wry_unglitch:
    "images/sprites/王霜/抱胸表情/抱胸(无奈.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed blank_unglitch:
    "images/sprites/王霜/抱胸表情/抱胸(面无表情.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws crossed default_unglitch:
    "images/sprites/王霜/抱胸表情/抱胸(默认.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand shocked_unglitch:
    "images/sprites/王霜/背手表情/背手(吃惊.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand smirk_unglitch:
    "images/sprites/王霜/背手表情/背手(坏笑.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand blank_unglitch:
    "images/sprites/王霜/背手表情/背手(面无表情).png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws backhand default_unglitch:
    "images/sprites/王霜/背手表情/背手(默认.png"
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 0.2
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image ws akimbo blank_glitchsoft:
    block:
        "images/sprites/王霜/叉腰表情/叉腰（面无表情.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/叉腰（面无表情_glitchsoft1.png"
        0.07
        "images/sprites/王霜/叉腰表情/叉腰（面无表情.png"
        0.08
        "images/sprites/王霜/glitch_soft/叉腰（面无表情_glitchsoft2.png"
        0.07
        repeat

image ws akimbo default_glitchsoft:
    block:
        "images/sprites/王霜/叉腰表情/叉腰（默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/叉腰（默认_glitchsoft1.png"
        0.07
        "images/sprites/王霜/叉腰表情/叉腰（默认.png"
        0.08
        "images/sprites/王霜/glitch_soft/叉腰（默认_glitchsoft2.png"
        0.07
        repeat

image ws crossed smirk_glitchsoft:
    block:
        "images/sprites/王霜/抱胸表情/抱胸(坏笑.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/抱胸(坏笑_glitchsoft1.png"
        0.07
        "images/sprites/王霜/抱胸表情/抱胸(坏笑.png"
        0.08
        "images/sprites/王霜/glitch_soft/抱胸(坏笑_glitchsoft2.png"
        0.07
        repeat

image ws crossed wry_glitchsoft:
    block:
        "images/sprites/王霜/抱胸表情/抱胸(无奈.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/抱胸(无奈_glitchsoft1.png"
        0.07
        "images/sprites/王霜/抱胸表情/抱胸(无奈.png"
        0.08
        "images/sprites/王霜/glitch_soft/抱胸(无奈_glitchsoft2.png"
        0.07
        repeat

image ws crossed default_glitchsoft:
    block:
        "images/sprites/王霜/抱胸表情/抱胸(默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/抱胸(默认_glitchsoft1.png"
        0.07
        "images/sprites/王霜/抱胸表情/抱胸(默认.png"
        0.08
        "images/sprites/王霜/glitch_soft/抱胸(默认_glitchsoft2.png"
        0.07
        repeat

image ws backhand smirk_glitchsoft:
    block:
        "images/sprites/王霜/背手表情/背手(坏笑.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/背手(坏笑_glitchsoft1.png"
        0.07
        "images/sprites/王霜/背手表情/背手(坏笑.png"
        0.08
        "images/sprites/王霜/glitch_soft/背手(坏笑_glitchsoft2.png"
        0.07
        repeat

image ws backhand default_glitchsoft:
    block:
        "images/sprites/王霜/背手表情/背手(默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/王霜/glitch_soft/背手(默认_glitchsoft1.png"
        0.07
        "images/sprites/王霜/背手表情/背手(默认.png"
        0.08
        "images/sprites/王霜/glitch_soft/背手(默认_glitchsoft2.png"
        0.07
        repeat

## 尤里娅（银白色沙漠段）。
image yl normal default = "images/sprites/尤里娅/尤利娅（默认）.png"
image yl normal evil1 = "images/sprites/尤里娅/尤利娅(邪恶笑1.png"
image yl normal evil2 = "images/sprites/尤里娅/尤利娅（邪恶笑2.png"
image yl normal scribble = "images/sprites/尤里娅/尤利娅（毛刺.png"
image yl normal smirk = "images/sprites/尤里娅/尤利娅(坏笑.png"
image yl corpse = "images/sprites/尤里娅/尤利娅尸首.png"

image yl normal default_glitch:
    choice:
        "images/sprites/尤里娅/glitch/尤利娅（默认）_glitch1.png"
    choice:
        "images/sprites/尤里娅/glitch/尤利娅（默认）_glitch2.png"
    choice:
        "images/sprites/尤里娅/glitch/尤利娅（默认）_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal smirk_glitch:
    choice:
        "images/sprites/尤里娅/glitch/尤利娅(坏笑_glitch1.png"
    choice:
        "images/sprites/尤里娅/glitch/尤利娅(坏笑_glitch2.png"
    choice:
        "images/sprites/尤里娅/glitch/尤利娅(坏笑_glitch3.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal default_unglitch:
    "images/sprites/尤里娅/尤利娅（默认）.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal evil1_unglitch:
    "images/sprites/尤里娅/尤利娅(邪恶笑1.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal evil2_unglitch:
    "images/sprites/尤里娅/尤利娅（邪恶笑2.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal scribble_unglitch:
    "images/sprites/尤里娅/尤利娅（毛刺.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

image yl normal smirk_unglitch:
    "images/sprites/尤里娅/尤利娅(坏笑.png"
    shader "game.sprite_glitch"
    u_sg_top 0.05
    u_sg_bot 0.22
    u_sg_dropout 0.0
    u_sg_amp 1.0
    easeout 0.5 u_sg_amp 0.0

## 半身近景（第一人称对视感）：头到腰占满屏，底部裁掉，水平居中。
transform ws_close:
    xalign 0.5
    yanchor 0.0
    ypos -50
    zoom 0.52

## 半身近景 + 小跳（【小跳】）。
transform ws_close_hop:
    xalign 0.5
    yanchor 0.0
    ypos -50
    zoom 0.52
    subpixel True
    pause 0.2
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 中景（虚空对视）：大小与店员立绘一致，居中。
transform ws_mid:
    xalign 0.5
    yanchor 0.0
    ypos 120
    zoom 0.42

## 中景 + 小跳（【小跳】）。
transform ws_mid_hop:
    xalign 0.5
    yanchor 0.0
    ypos 120
    zoom 0.42
    subpixel True
    pause 0.2
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 沙漠中景（银白色沙漠段）：偏右站位 = 走路进场落点。
transform ws_desert:
    xanchor 0.5
    xpos 0.76
    yanchor 0.0
    ypos 120
    zoom 0.38
    u_sg_amp 0.0
    u_sg_dropout 0.0

## 沙漠中景 + 小跳（【小跳】）。
transform ws_desert_hop:
    xanchor 0.5
    xpos 0.76
    yanchor 0.0
    ypos 120
    zoom 0.38
    u_sg_amp 0.0
    u_sg_dropout 0.0
    subpixel True
    pause 0.2
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 沙漠中景 + glitch 物化入场（跑动 sequence 结束后的非自然重新登场）。
## ★紧随其后的同一交互内立绘 show 会省略 at 列表★（同走路窗口的处理），
## 否则替换回 ws_desert 时按尾部对齐继承中途值、动画冻在半路。
transform ws_desert_glitchin:
    xanchor 0.5
    xpos 0.76
    yanchor 0.0
    ypos 120
    zoom 0.38
    u_sg_amp 0.0
    u_sg_dropout 0.0
    mesh True
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_amp 1.0
    u_sg_dropout 1.0
    parallel:
        easeout 0.5 u_sg_amp 0.0
    parallel:
        easeout 0.4 u_sg_dropout 0.0

## 【从当前位置(缓缓)走到屏幕中心，立绘略微放大】：从走路落点走到屏幕
## 中心，步频比走入略快，边走边微放大（走近镜头）。窗口语义同走路 ——
## 后续 show 省略 at，人留在中心。
transform ws_desert_center_walk:
    subpixel True
    xanchor 0.5
    xpos 0.76
    yanchor 0.0
    ypos 120
    zoom 0.38
    u_sg_amp 0.0
    u_sg_dropout 0.0
    parallel:
        linear 2.0 xpos 0.5
    parallel:
        ease 2.0 zoom 0.5
    parallel:
        block:
            easeout 0.275 yoffset -12
            easein 0.275 yoffset 0
            repeat 4

## 【立绘回归原来大小】：zoom 从继承的放大值缓回常规。★只用于紧接
## 中心走之后的 re-show★ —— zoom 初值靠尾部对齐继承，冷启动会从 1.0
## 缩下来。yoffset 归零兜底（快速点击时可能继承到迈步中途的起伏值）。
transform ws_desert_center:
    xanchor 0.5
    xpos 0.5
    yanchor 0.0
    ypos 120
    yoffset 0
    u_sg_amp 0.0
    u_sg_dropout 0.0
    ease 0.5 zoom 0.38

## 【尤里娅登场】：王霜平滑滑回右侧让位。xpos 从尾部对齐继承的当前值
## ease 过去；zoom 只是兜底归位（正常流程她已是 WS_DESERT_ZOOM，无缩放
## 动作）。无步态起伏 —— 是"画面重新构图"不是走路。
## ★同 ws_desert_center：只用于窗口内 re-show，冷启动无意义★。
transform ws_desert_slide_right:
    xanchor 0.5
    yanchor 0.0
    ypos 120
    yoffset 0
    u_sg_amp 0.0
    u_sg_dropout 0.0
    parallel:
        ease 0.8 xpos 0.76
    parallel:
        ease 0.8 zoom 0.38

## 尤里娅：左侧偏中，与右侧的王霜（ws_desert）同台等高。
transform yl_mid:
    xanchor 0.5
    xpos 0.26
    yanchor 0.0
    ypos 110
    zoom 0.37
    u_sg_amp 0.0
    u_sg_dropout 0.0

## 尤里娅 glitch 物化入场（消失后的重现 —— 消失的镜像）。
transform yl_mid_glitchin:
    xanchor 0.5
    xpos 0.26
    yanchor 0.0
    ypos 110
    zoom 0.37
    u_sg_amp 0.0
    u_sg_dropout 0.0
    mesh True
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_amp 1.0
    u_sg_dropout 1.0
    parallel:
        easeout 0.5 u_sg_amp 0.0
    parallel:
        easeout 0.4 u_sg_dropout 0.0

## 【尤里娅消失】：异常消失 —— 全身撕裂渐强 + 随机行序逐行掐断
## （信号被掐，不是 fade out）。非阻塞；行全部丢完即不可见，不发
## hide —— 下次 show / scene 自然接管（同店员退场的处理）。
transform yl_vanish:
    xanchor 0.5
    xpos 0.26
    yanchor 0.0
    ypos 110
    zoom 0.37
    u_sg_amp 0.0
    u_sg_dropout 0.0
    mesh True
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_dropout 0.0
    u_sg_amp 0.0
    parallel:
        easein 0.45 u_sg_amp 1.0
    parallel:
        pause 0.113
        easein 0.338 u_sg_dropout 1.0

## 【尤里娅异变】第一拍：人形高频痉挛 + 身体异常纵向拉伸抽动 +
## 撕裂渐强 + 血色从内漫延淹没全身 —— 转换器配 hard_pause 锁住整拍，
## 红闪（mutation_flash）后第二拍尸首（yl_corpse_in）扑入。
transform yl_mutate:
    xanchor 0.5
    xpos 0.26
    yanchor 0.0
    ypos 110
    zoom 0.37
    u_sg_amp 0.0
    u_sg_dropout 0.0
    mesh True
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_dropout 0.0
    u_sg_amp 0.0
    subpixel True
    matrixcolor TintMatrix("#ffffff")
    parallel:
        easein 0.7 u_sg_amp 1.0
    parallel:
        # 血色漫延：结构相同的 TintMatrix 之间逐参数插值
        ease 0.7 matrixcolor TintMatrix("#b32020")
    parallel:
        # 高频痉挛
        block:
            linear 0.04 xoffset -12
            linear 0.04 xoffset 12
            repeat
    parallel:
        # 身体异常拉伸抽动（血肉在错误地重组）
        block:
            easeout 0.16 yzoom 1.07
            easein 0.12 yzoom 0.96
            repeat
    parallel:
        pause 0.42
        easein 0.28 u_sg_dropout 0.6

## 尸首形态（横构图缝合怪）：头与王霜立绘的头等大，左侧骨头出画。
transform yl_corpse_pos:
    xanchor 0.5
    xpos 0.15
    yanchor 0.0
    ypos -330
    zoom 0.7

## 尸首 glitch 物化入场（跑动 sequence 结束后的重新登场）。
transform yl_corpse_glitchin:
    xanchor 0.5
    xpos 0.15
    yanchor 0.0
    ypos -330
    zoom 0.7
    mesh True
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_amp 1.0
    u_sg_dropout 1.0
    parallel:
        easeout 0.5 u_sg_amp 0.0
    parallel:
        easeout 0.4 u_sg_dropout 0.0

## 异变第二拍：尸首从深处扑到眼前 —— 以头部为锚点、zoom 从 LUNGE 倍
## 猛冲到位（脸原地朝你放大）+ 撕裂收敛落定（配红闪余韵和 fx_shock）。
## 锚点坐标由 YL_CORPSE_HEAD/IMG 换算，落位与 yl_corpse_pos 完全一致。
transform yl_corpse_in:
    # 从 yl_mutate 尾部对齐继承来的痉挛/拉伸/血色中间值全部显式复位
    xoffset 0
    yzoom 1.0
    matrixcolor TintMatrix("#ffffff")
    xanchor 0.68
    yanchor 0.32
    xpos 798
    ypos 292
    mesh True   # 同 sg_full：隔离图内同名 shader + 作用带按整图算
    shader "game.sprite_glitch"
    u_sg_top 0.0
    u_sg_bot 1.0
    u_sg_dropout 0.0
    u_sg_amp 1.0
    zoom 0.385
    parallel:
        easeout 0.22 zoom 0.7
    parallel:
        easeout 0.4 u_sg_amp 0.0

## 异变切换瞬间的满屏红闪：show 即峰值、随后褪尽。scene 时被清掉。
image mutation_flash:
    Solid("#c81616", xysize=(1920, 1080))
    alpha 0.85
    linear 0.35 alpha 0.0

## 沙漠走路进场（【王霜走路进场】）：左缘外走到画面偏右，水平匀速 +
## 每步一次起伏。落点即站定位置 —— 走路窗口内的后续姿势 show 不带 at
## 列表，沿用本 transform 的落点（见 convert_script.py 走路窗口逻辑）。
## subpixel：起伏只有十几像素，不开亚像素会整像素跳格。
transform ws_desert_walk:
    subpixel True
    xanchor 0.5
    xpos -0.3
    yanchor 0.0
    ypos 120
    zoom 0.38
    parallel:
        linear 10.0 xpos 0.76
    parallel:
        block:
            easeout 0.3 yoffset -12
            easein 0.3 yoffset 0
            repeat 17

## 店员（王霜复制体，甜品店段）：右侧正立。
transform ws_clerk_right:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42

## 店员1入场：从屏幕下方升上来（非阻塞，与店员2 的降下对称）。
transform ws_clerk_right_enter:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    yoffset 1100
    ease 0.7 yoffset 0

## 店员1退场：垂直平移沉出画面（非阻塞）。
transform ws_clerk_right_exit:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    ease 0.7 yoffset 1100

## 店员1 + 小跳（【小跳】）。
transform ws_clerk_right_hop:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    subpixel True
    pause 0.2
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 店员2：左侧从天花板倒吊（rotate 180，底边=头部下沿）。
transform ws_clerk_ceiling:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42

## 店员2入场：从天花板上方倒吊降下（非阻塞）。
transform ws_clerk_ceiling_enter:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    yoffset -1100
    ease 0.7 yoffset 0

## 店员2退场：垂直平移收回天花板（非阻塞）。
transform ws_clerk_ceiling_exit:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    ease 0.7 yoffset -1100

## 店员2 + 小跳（【小跳】）：倒吊着向上（天花板方向）弹一下。
transform ws_clerk_ceiling_hop:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    subpixel True
    pause 0.2
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0
