## AUTO-GENERATED by convert_script.py — 不要手改，重跑转换器会覆盖。
## 王霜立绘：素材在本目录下按 <姿势>(<表情>.png 命名，扫描自动注册。
## 摆位参数改 convert_script.py 里的 WS_* 常量。

image ws akimbo proud = "images/sprites/叉腰表情/叉腰（得意.png"
image ws akimbo blank = "images/sprites/叉腰表情/叉腰（面无表情.png"
image ws akimbo default = "images/sprites/叉腰表情/叉腰（默认.png"
image ws crossed smirk = "images/sprites/抱胸表情/抱胸(坏笑.png"
image ws crossed wry = "images/sprites/抱胸表情/抱胸(无奈.png"
image ws crossed blank = "images/sprites/抱胸表情/抱胸(面无表情.png"
image ws crossed default = "images/sprites/抱胸表情/抱胸(默认.png"
image ws backhand shocked = "images/sprites/背手表情/背手(吃惊.png"
image ws backhand smirk = "images/sprites/背手表情/背手(坏笑.png"
image ws backhand blank = "images/sprites/背手表情/背手(面无表情).png"
image ws backhand default = "images/sprites/背手表情/背手(默认.png"

image ws akimbo blank_glitch:
    "images/sprites/glitch/叉腰（面无表情_glitch1.png"
    0.12
    "images/sprites/glitch/叉腰（面无表情_glitch2.png"
    0.12
    "images/sprites/glitch/叉腰（面无表情_glitch3.png"
    0.12
    repeat

image ws akimbo default_glitch:
    "images/sprites/glitch/叉腰（默认_glitch1.png"
    0.12
    "images/sprites/glitch/叉腰（默认_glitch2.png"
    0.12
    "images/sprites/glitch/叉腰（默认_glitch3.png"
    0.12
    repeat

image ws crossed smirk_glitch:
    "images/sprites/glitch/抱胸(坏笑_glitch1.png"
    0.12
    "images/sprites/glitch/抱胸(坏笑_glitch2.png"
    0.12
    "images/sprites/glitch/抱胸(坏笑_glitch3.png"
    0.12
    repeat

image ws crossed wry_glitch:
    "images/sprites/glitch/抱胸(无奈_glitch1.png"
    0.12
    "images/sprites/glitch/抱胸(无奈_glitch2.png"
    0.12
    "images/sprites/glitch/抱胸(无奈_glitch3.png"
    0.12
    repeat

image ws crossed default_glitch:
    "images/sprites/glitch/抱胸(默认_glitch1.png"
    0.12
    "images/sprites/glitch/抱胸(默认_glitch2.png"
    0.12
    "images/sprites/glitch/抱胸(默认_glitch3.png"
    0.12
    repeat

image ws backhand smirk_glitch:
    "images/sprites/glitch/背手(坏笑_glitch1.png"
    0.12
    "images/sprites/glitch/背手(坏笑_glitch2.png"
    0.12
    "images/sprites/glitch/背手(坏笑_glitch3.png"
    0.12
    repeat

image ws backhand default_glitch:
    "images/sprites/glitch/背手(默认_glitch1.png"
    0.12
    "images/sprites/glitch/背手(默认_glitch2.png"
    0.12
    "images/sprites/glitch/背手(默认_glitch3.png"
    0.12
    repeat

image ws akimbo blank_glitchsoft:
    block:
        "images/sprites/叉腰表情/叉腰（面无表情.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/叉腰（面无表情_glitchsoft1.png"
        0.07
        "images/sprites/叉腰表情/叉腰（面无表情.png"
        0.08
        "images/sprites/glitch_soft/叉腰（面无表情_glitchsoft2.png"
        0.07
        repeat

image ws akimbo default_glitchsoft:
    block:
        "images/sprites/叉腰表情/叉腰（默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/叉腰（默认_glitchsoft1.png"
        0.07
        "images/sprites/叉腰表情/叉腰（默认.png"
        0.08
        "images/sprites/glitch_soft/叉腰（默认_glitchsoft2.png"
        0.07
        repeat

image ws crossed smirk_glitchsoft:
    block:
        "images/sprites/抱胸表情/抱胸(坏笑.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/抱胸(坏笑_glitchsoft1.png"
        0.07
        "images/sprites/抱胸表情/抱胸(坏笑.png"
        0.08
        "images/sprites/glitch_soft/抱胸(坏笑_glitchsoft2.png"
        0.07
        repeat

image ws crossed wry_glitchsoft:
    block:
        "images/sprites/抱胸表情/抱胸(无奈.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/抱胸(无奈_glitchsoft1.png"
        0.07
        "images/sprites/抱胸表情/抱胸(无奈.png"
        0.08
        "images/sprites/glitch_soft/抱胸(无奈_glitchsoft2.png"
        0.07
        repeat

image ws crossed default_glitchsoft:
    block:
        "images/sprites/抱胸表情/抱胸(默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/抱胸(默认_glitchsoft1.png"
        0.07
        "images/sprites/抱胸表情/抱胸(默认.png"
        0.08
        "images/sprites/glitch_soft/抱胸(默认_glitchsoft2.png"
        0.07
        repeat

image ws backhand smirk_glitchsoft:
    block:
        "images/sprites/背手表情/背手(坏笑.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/背手(坏笑_glitchsoft1.png"
        0.07
        "images/sprites/背手表情/背手(坏笑.png"
        0.08
        "images/sprites/glitch_soft/背手(坏笑_glitchsoft2.png"
        0.07
        repeat

image ws backhand default_glitchsoft:
    block:
        "images/sprites/背手表情/背手(默认.png"
        choice:
            pause 1.8
        choice:
            pause 2.4
        choice:
            pause 3.0
        "images/sprites/glitch_soft/背手(默认_glitchsoft1.png"
        0.07
        "images/sprites/背手表情/背手(默认.png"
        0.08
        "images/sprites/glitch_soft/背手(默认_glitchsoft2.png"
        0.07
        repeat

## 半身近景（第一人称对视感）：头到腰占满屏，底部裁掉，水平居中。
transform ws_close:
    xalign 0.5
    yanchor 0.0
    ypos -50
    zoom 0.52

## 半身近景 + 小跳（【小跳】）。
transform ws_close_hop:
    xalign 0.5
    yanchor 0.0
    ypos -50
    zoom 0.52
    subpixel True
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 中景（沙漠桥段/虚空对视）：大小与店员立绘一致。
transform ws_mid:
    xalign 0.5
    yanchor 0.0
    ypos 120
    zoom 0.42

## 中景 + 小跳（【小跳】）。
transform ws_mid_hop:
    xalign 0.5
    yanchor 0.0
    ypos 120
    zoom 0.42
    subpixel True
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 沙漠走路进场（【王霜走路进场】）：左缘外走到画面偏右，水平匀速 +
## 每步一次起伏。落点即站定位置 —— 走路窗口内的后续姿势 show 不带 at
## 列表，沿用本 transform 的落点（见 convert_script.py 走路窗口逻辑）。
## subpixel：起伏只有十几像素，不开亚像素会整像素跳格。
transform ws_desert_walk:
    subpixel True
    xanchor 0.5
    xpos -0.3
    yanchor 0.0
    ypos 120
    zoom 0.42
    parallel:
        linear 10.0 xpos 0.7
    parallel:
        block:
            easeout 0.3 yoffset -12
            easein 0.3 yoffset 0
            repeat 17

## 店员（王霜复制体，甜品店段）：右侧正立。
transform ws_clerk_right:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42

## 店员1入场：从屏幕下方升上来（非阻塞，与店员2 的降下对称）。
transform ws_clerk_right_enter:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    yoffset 1100
    ease 0.7 yoffset 0

## 店员1退场：垂直平移沉出画面（非阻塞）。
transform ws_clerk_right_exit:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    ease 0.7 yoffset 1100

## 店员1 + 小跳（【小跳】）。
transform ws_clerk_right_hop:
    xanchor 0.5
    xpos 0.82
    yanchor 0.0
    ypos 120
    zoom 0.42
    subpixel True
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0

## 店员2：左侧从天花板倒吊（rotate 180，底边=头部下沿）。
transform ws_clerk_ceiling:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42

## 店员2入场：从天花板上方倒吊降下（非阻塞）。
transform ws_clerk_ceiling_enter:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    yoffset -1100
    ease 0.7 yoffset 0

## 店员2退场：垂直平移收回天花板（非阻塞）。
transform ws_clerk_ceiling_exit:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    ease 0.7 yoffset -1100

## 店员2 + 小跳（【小跳】）：倒吊着向上（天花板方向）弹一下。
transform ws_clerk_ceiling_hop:
    rotate 180
    xanchor 0.5
    xpos 0.18
    yanchor 1.0
    ypos 960
    zoom 0.42
    subpixel True
    easeout 0.14 yoffset -28
    easein 0.12 yoffset 0
